# Generated by Django 4.2.7 on 2025-09-23 17:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_realisation', models.DateTimeField(auto_now_add=True)),
                ('temps_passe_sec', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('note_obtenue', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ABANDONNE', 'Abandonné')], default='EN_COURS', max_length=10)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcours', to='quizzes.questionnaire')),
            ],
            options={
                'verbose_name': 'Parcours',
                'verbose_name_plural': 'Parcours',
                'db_table': 'parcours',
                'ordering': ['-date_realisation'],
            },
        ),
        migrations.CreateModel(
            name='ReponseUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_utilisateur', to='responses.parcours')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_utilisateur', to='quizzes.question')),
            ],
            options={
                'verbose_name': 'Réponse utilisateur',
                'verbose_name_plural': 'Réponses utilisateur',
                'db_table': 'reponse_utilisateur',
            },
        ),
        migrations.CreateModel(
            name='ReponseUtilisateurSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponse_utilisateur_selections', to='quizzes.reponse')),
                ('reponse_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='responses.reponseutilisateur')),
            ],
            options={
                'verbose_name': 'Sélection réponse utilisateur',
                'verbose_name_plural': 'Sélections réponses utilisateur',
                'db_table': 'reponse_utilisateur_selection',
            },
        ),
    ]
