# Generated by Django 4.2.7 on 2025-09-23 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('responses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcours',
            name='stagiaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcours', to='users.stagiaire'),
        ),
        migrations.AlterUniqueTogether(
            name='reponseutilisateurselection',
            unique_together={('reponse_utilisateur', 'reponse')},
        ),
        migrations.AlterUniqueTogether(
            name='reponseutilisateur',
            unique_together={('parcours', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='parcours',
            unique_together={('stagiaire', 'questionnaire')},
        ),
    ]
