# Generated by Django 4.2.7 on 2025-09-23 23:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
        ('users', '0001_initial'),
        ('responses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcours',
            name='note_sur_20',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='parcours',
            name='penalites_appliquees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parcours',
            name='temps_moyen_par_question',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='reponseutilisateur',
            name='date_reponse',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reponseutilisateur',
            name='score_obtenu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='reponseutilisateur',
            name='temps_reponse_sec',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='AnalyseStagiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_questionnaires_termines', models.IntegerField(default=0)),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('note_moyenne_sur_20', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('temps_total_formation', models.IntegerField(default=0)),
                ('niveau_global', models.CharField(default='Débutant', max_length=20)),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('stagiaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyse', to='users.stagiaire')),
            ],
            options={
                'verbose_name': 'Analyse stagiaire',
                'verbose_name_plural': 'Analyses stagiaires',
                'db_table': 'analyse_stagiaire',
            },
        ),
        migrations.CreateModel(
            name='AnalyseQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_passages', models.IntegerField(default=0)),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('note_mediane', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('temps_moyen_completion', models.IntegerField(default=0)),
                ('taux_abandon', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('questionnaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyse', to='quizzes.questionnaire')),
            ],
            options={
                'verbose_name': 'Analyse questionnaire',
                'verbose_name_plural': 'Analyses questionnaires',
                'db_table': 'analyse_questionnaire',
            },
        ),
        migrations.CreateModel(
            name='AnalyseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tentatives', models.IntegerField(default=0)),
                ('nombre_reussites', models.IntegerField(default=0)),
                ('taux_reussite', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('temps_moyen_reponse', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyse', to='quizzes.question')),
            ],
            options={
                'verbose_name': 'Analyse question',
                'verbose_name_plural': 'Analyses questions',
                'db_table': 'analyse_question',
            },
        ),
    ]
